# Generated by Django 4.2.3 on 2023-07-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='technical_downtime',
            field=models.IntegerField(default=None),
        ),
    ]
