# Generated by Django 4.2.3 on 2023-07-29 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_claim_technical_downtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='technical_downtime',
        ),
        migrations.AlterField(
            model_name='machine',
            name='controlled_bridge_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.controlledbridgemodel'),
        ),
    ]
