# Generated by Django 4.2.3 on 2023-08-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_machine_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='service_company',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='service_company',
        ),
    ]
