# Generated by Django 4.2.3 on 2023-08-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_claim_service_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='technical_downtime',
            field=models.IntegerField(null=True),
        ),
    ]
