# Generated by Django 4.2.3 on 2023-08-03 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_claim_technical_downtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='service_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.servicecompany'),
        ),
    ]
